### PR TITLE
Start game manually by clicking on 'Start'

### PR DESCRIPTION
**Pull request by olya-d**

### CODE REVIEW

**Comment by anvoz** [comment]
Thanks. I am going add the game introduction to the center screen this weekend.

**Comment by olya-d** [comment]
My pleasure. I would like to contribute to your project, please, if there is something specific you want other people to work on - message me.

**Comment by anvoz** [comment]
Thank you. Please send me email at anvo4888@gmail.com so we could talk more about this project.

**Comment by olya-d** [comment]
Hi!

—

**Comment by anvoz** [comment]
I don't think this works. Please email me at anvo4888@gmail.com. Don't comment here.

**Pull request merged**
